# Generated by Django 5.2.15 on 2026-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('complexity', models.PositiveSmallIntegerField(default=2, help_text='Cognitive complexity 1 (routine) – 5 (very complex)')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_unplanned', models.BooleanField(default=False, help_text='Unexpected task (legacy TacheImprevue)')),
                ('reference', models.CharField(blank=True, help_text='Calibrated-task reference (legacy TacheCalibree)', max_length=100)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('score', models.FloatField(help_text='0 (idle) – 100 (critical)')),
                ('level', models.CharField(choices=[('OK', 'Sustainable'), ('ELEVATED', 'Elevated'), ('HIGH', 'High'), ('BURNOUT_RISK', 'Burnout risk')], max_length=20)),
                ('components', models.JSONField(default=dict, help_text='Per-dimension contributions used in the score.')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkdaySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('date', models.DateField()),
                ('meetings_count', models.PositiveSmallIntegerField(default=0)),
                ('interruptions_count', models.PositiveSmallIntegerField(default=0)),
                ('stress_level', models.PositiveSmallIntegerField(default=3, help_text='Self-reported stress 1 (calm) – 5 (overwhelmed)')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('level', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='workload.workloadscore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
